# HDCluster
# @author caizi
apiVersion: v1
kind: Service
metadata:
  name: mysql-hs
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: server
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-cs
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: client
  selector:
    app: mysql
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mysql-pdb
spec:
  selector:
    matchLabels:
      app: mysql
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-hs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: kubernetes-mysql
        imagePullPolicy: IfNotPresent
        image: "mysql:8.0.31"
        resources:
          requests:
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: $MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: server
        - containerPort: 3306
          name: client
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          failureThreshold: 5
          periodSeconds: 60
        startupProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          failureThreshold: 60
          periodSeconds: 10
        volumeMounts:
        - name: mysqlpvc
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysqlpvc
      annotations:
        volume.beta.kubernetes.io/storage-class: nfs-client
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 5120Mi          
