apiVersion: v1
kind: Service
metadata:
  name: site-hs
  labels:
    app: site
spec:
  ports:
  - port: 9866
    name: server
  clusterIP: None
  selector:
    app: site
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: site-pdb
spec:
  selector:
    matchLabels:
      app: site
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: site
spec:
  selector:
    matchLabels:
      app: site
  serviceName: site-hs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: kubernetes-site
        imagePullPolicy: IfNotPresent
        image: "caiziale/hdcluster:1.0.0.Beta"
        resources:
          requests:
        ports:
        - containerPort: 9866
          name: server
        command:
        - sh
        - -c
        - "create_site.sh \
          --servers=3 \
          --mysqlpassword=$MYSQL_PASSWORD"
        volumeMounts:
          - name: nfs-site
            mountPath: "/mnt"
      volumes:
        - name: nfs-site
          persistentVolumeClaim:
            claimName: hp-claim          
