# HDCluster
# @author caizi
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hp-claim
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
